{{- if .Values.romm.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.romm.config.name | default "romm-config-file" }}
  labels:
    {{- include "romm.labels" (dict "Chart" $.Chart "Release" $.Release "Values" $.Values) | nindent 4 }}
data:
  config.yml: |
{{ .Values.romm.config.data | toYaml | indent 4 }}
{{- end }}
