{{- if .Values.rommConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.rommConfig.name | default "romm-config-file" }}
  labels:
    {{- include "app.labels" (dict "name" (default "romm-config-file" .Values.rommConfig.name) "Values" $.Values "Release" $.Release) | nindent 4 }}
data:
  config.yml: |
{{ .Values.rommConfig.config | indent 4 }}
{{- end }}
