{{- if .Values.romm.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.romm.config.name | default "romm-config-file" }}
  labels:
    {{- include "romm.labels" . | nindent 4 }}
data:
  config.yml: |
    test: value
{{- end }}
